// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * PresetSize represents a window size preset
 */
export class PresetSize {
    "id": string;
    "width": number;
    "height": number;

    /** Creates a new PresetSize instance. */
    constructor($$source: Partial<PresetSize> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("width" in $$source)) {
            this["width"] = 0;
        }
        if (!("height" in $$source)) {
            this["height"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PresetSize instance from a string or object.
     */
    static createFrom($$source: any = {}): PresetSize {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PresetSize($$parsedSource as Partial<PresetSize>);
    }
}
