// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./util/store/models.js";

export function CheckPermission(): $CancellablePromise<boolean> {
    return $Call.ByID(2828054571);
}

export function ClosePermissionWindow(): $CancellablePromise<void> {
    return $Call.ByID(1729154135);
}

export function GetPresets(): $CancellablePromise<store$0.PresetSize[]> {
    return $Call.ByID(390496076).then(($result: any) => {
        return $$createType1($result);
    });
}

export function RequestPermission(): $CancellablePromise<void> {
    return $Call.ByID(3154168290);
}

export function SetPresets(presets: store$0.PresetSize[]): $CancellablePromise<void> {
    return $Call.ByID(895970328, presets);
}

// Private type creation functions
const $$createType0 = store$0.PresetSize.createFrom;
const $$createType1 = $Create.Array($$createType0);
