// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import {Call as $Call, Create as $Create} from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as store$0 from "./util/store/models.js";

export function CheckPermission(): Promise<boolean> & { cancel(): void } {
    let $resultPromise = $Call.ByID(2828054571) as any;
    return $resultPromise;
}

export function ClosePermissionWindow(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1729154135) as any;
    return $resultPromise;
}

export function GetPresets(): Promise<store$0.PresetSize[]> & { cancel(): void } {
    let $resultPromise = $Call.ByID(390496076) as any;
    let $typingPromise = $resultPromise.then(($result: any) => {
        return $$createType1($result);
    }) as any;
    $typingPromise.cancel = $resultPromise.cancel.bind($resultPromise);
    return $typingPromise;
}

export function Greet(name: string): Promise<string> & { cancel(): void } {
    let $resultPromise = $Call.ByID(1411160069, name) as any;
    return $resultPromise;
}

export function RequestPermission(): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(3154168290) as any;
    return $resultPromise;
}

export function SetPresets(presets: store$0.PresetSize[]): Promise<void> & { cancel(): void } {
    let $resultPromise = $Call.ByID(895970328, presets) as any;
    return $resultPromise;
}

// Private type creation functions
const $$createType0 = store$0.PresetSize.createFrom;
const $$createType1 = $Create.Array($$createType0);
